require('options')
require('plugins')
require('colorscheme')
require('lsp')
require('filesystem')
require('keymaps.splits')
require('keymaps.fuzzy')
require('keymaps.snippets')
require('keymaps.qol')
require('config.nvim-cmp')
-- require('config.treesitter')
